import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { auth } from "@/auth";
import Administrator from "./admin/page";
import SWRConfigContext from "@/context/SWRConfigContext";
import { CompanyProvider } from "@/context/CompanyContext";

const openSans = Open_Sans({
  subsets: ["latin"],
});
const session = await auth()
// console.log('session_layout: ',session)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
}
export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en" className={openSans.className}>
      <body className=" w-full max-w- screen-xl overflow-auto mx-auto bg-fuchsia-100">
        <Administrator>
          <header className="sticky top-0 bg-white z-10 border-b">
            <Navbar />
          </header>
          <main className=" w-full flex justify-center min-h-full">
            <SWRConfigContext>
              <CompanyProvider>
               {children}
              </CompanyProvider>
            </SWRConfigContext>
          </main>
        </Administrator>
      </body>
    </html>
  );
}
